[package]
name = "monarchy-mcmonarch-bot"
version = "0.1.0"
authors = ["Alexander Launi <alex.launi@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
color-eyre = "0.5.4"
futures = "0.3.5"
